apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-deployment
  labels:
    app: homework-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: homework-service
  template:
    metadata:
      labels:
        app: homework-service
    spec:
      containers:
      - name: homework-service
        image: sessill/homework-docker:latest
        ports:
        - containerPort: 8000
